// Generated by CoffeeScript 1.4.0
(function() {

  describe("Challenge 1", function() {
    beforeEach(function() {
      setFixtures("<div class=\"challenge1\">\n  <div class=\"description\">\n    <h2>Challenge 1</h2>\n    <p>Make the following HTML code match the following image using only CSS.</p>\n    <img src=\"http://dl.dropbox.com/u/26385406/challenge1.png\"  />\n  </div>\n\n  <div class=\"code\">\n    <div>I am first</div>\n    <div>I am in the middle</div>\n    <div>I am last</div>\n  </div>\n</div>");
      return this.positions = $(".challenge1 .code div");
    });
    it("should have floated divs, 100px wide, 100 px tall", function() {
      return expect(this.positions).toHaveCss({
        width: "100px",
        float: "left",
        height: "100px"
      });
    });
    it("should have thin, white, Helvetica or sans-serif font", function() {
      return expect(this.positions).toHaveCss({
        'font-family': "Helvetica, sans-serif",
        'font-weight': "300",
        color: "rgb(255, 255, 255)"
      });
    });
    return it("should have divs with radial gradient backgrounds", function() {
      return this.positions.each(function(idx, position) {
        var backgroundColor;
        backgroundColor = $(position).css('background');
        return expect(backgroundColor).toContainTextValue('radial');
      });
    });
  });

}).call(this);
