// Generated by CoffeeScript 1.4.0
(function() {

  describe("Challenge 2", function() {
    beforeEach(function() {
      setFixtures("<div class=\"challenge2\">\n  <div class=\"description\">\n      <h2>Challenge 2</h2>\n      <p>Make the following HTML code match the following image using only CSS.</p>\n      <img src=\"http://dl.dropbox.com/u/26385406/challenge2.png\"  />\n  </div>\n\n  <div class=\"code\">\n      <div>I am first</div><div>I am in the middle</div><div>I am last</div>\n      <div>I am first</div><div>I am in the middle</div><div>I am last</div>\n  </div>\n</div>");
      return this.positions = $(".challenge2 .code div");
    });
    it("puts first and fourth divs on the left", function() {
      return this.positions.filter(function(idx) {
        return idx % 3 === 0;
      }).each(function(idx, position) {
        position = $(position);
        return expect(position).toHaveCss({
          float: "left"
        });
      });
    });
    it("puts third and sixth divs on the right", function() {
      return this.positions.filter(function(idx) {
        return idx % 3 === 2;
      }).each(function(idx, position) {
        position = $(position);
        return expect(position).toHaveCss({
          float: "right"
        });
      });
    });
    return it("puts the second and fifth divs in the center", function() {
      return this.positions.filter(function(idx) {
        return idx % 3 === 1;
      }).each(function(idx, position) {
        position = $(position);
        return expect(position).toHaveCss({
          position: "absolute"
        });
      });
    });
  });

}).call(this);
