// Generated by CoffeeScript 1.4.0
(function() {

  Array.prototype.findConsecutiveRuns = function() {
    var consecutives, currentVal, diff, idx, nextVal, secondIdx, thirdIdx, _i, _len;
    consecutives = [];
    for (idx = _i = 0, _len = this.length; _i < _len; idx = ++_i) {
      currentVal = this[idx];
      secondIdx = idx + 1;
      thirdIdx = secondIdx + 1;
      if (thirdIdx <= this.length - 1) {
        nextVal = this[secondIdx];
        diff = nextVal - currentVal;
        if ((diff === 1 || diff === (-1)) && this[thirdIdx] === (this[secondIdx] + diff)) {
          consecutives.push(idx);
        }
      }
    }
    if (consecutives.length > 0) {
      return consecutives;
    }
    return null;
  };

}).call(this);
